server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/EstebenGuio/java-ms
          search-path: config-data
  application:
    name: config-server