server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/EstebenGuio/java-ms
          search-paths: config-data
  application:
    name: config-server